### PR TITLE
Submit link

### PR DESCRIPTION
**Pull request by captainbland**
This is just a straight-up adaptation of submit self post.

### CODE REVIEW

**Comment by captainbland** [comment]
Need to add a test before merge

**Comment by IntrepidPig** [comment]
Thanks for the PR. I probably won't be able to get to it until this weekend but from what I've seen, it looks great. Sorry this project has been moving kind of slow lately, I've gotten really busy for the past and next few weeks, and I've had other projects occupying my weekends, but I'm so glad to see this one getting some attention.

**Comment by IntrepidPig** [comment]
Was procrastinating merging this because I'm not exactly sure how I'll work merging it with the upstream develop branch, but I guess I'll just cross that bridge when I get there. Thanks for the PR, so sorry it sat for so long.

**Comment by captainbland** [comment]
Hey no worries! I mean I only just spotted this now. :)

**Pull request merged**
